<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form action="controllers/user-form.php" method="post">
  <ul>
    <li>
      <label for="mail">Email</label>
      <input type="email" id="mail" name="mail" />
    </li>
    <li>
      <label for="pass">Password</label>
      <input type="password" id="pass" name="pass" />
    </li>
    <li>
      <label for="confirm">Confimation</label>
      <input type="password" id="confirm" name="confirm" />
    </li>
    <li>
      <label for="checkbox">Newsletter</label>
      <input type="checkbox" id="checkbox" name="checkbox" />
    </li>
    <li>
      <button type="submit">Envoyer</button>
    </li>
  </ul>
</form>

</main>
