<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>

<body>
    <h1>Connexion</h1>

    <form action="logic/login.php" method="POST">
        <fieldset>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
        </fieldset>

        <fieldset>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>
        </fieldset>

        <button type="submit">Se connecter</button>
    </form>
</body>

</html>