<!DOCTYPE html>
<html lang="<?= $_SESSION["lang"] ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $this->translator->translate("site_title") ?></title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
              crossorigin="anonymous">
        <link href="assets/style.css" rel="stylesheet" />
    </head>
    <body class="container-fluid p-0">
        <header>
            <nav class="px-2 navbar navbar-expand-lg bg-body-tertiary">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=home"><?= $this->translator->translate("nav_home_link") ?></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <?= $this->translator->translate("nav_Category_link") ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#"><?= $this->translator->translate("nav_development_link") ?></a></li>
                            <li><a class="dropdown-item" href="#"><?= $this->translator->translate("nav_design_link") ?></a></li>
                            <li><a class="dropdown-item" href="#"><?= $this->translator->translate("nav_accessibility_link") ?></a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=register"><?= $this->translator->translate("nav_register_link") ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=login"><?= $this->translator->translate("nav_login_link") ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=logout"><?= $this->translator->translate("nav_logout_link") ?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?route=switch-lang"><?= $this->translator->translate("nav_switch_link") ?></a>
                    </li>
                    <?php if (isset($_SESSION['user'])) { ?>
                        <li id="username"><?= $_SESSION['username'] ?></li>
                    <?php } ?>
                </ul>
            </nav>
        </header>

        <?php require "templates/$template.phtml"; ?>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    </body>
</html>