<main id="register" class="container py-5 px-3">
    <?php
    if(isset($_SESSION["error-message"]))
    {
    ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <?= $_SESSION["error-message"] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php
    }
    ?>
    <h1 class="mb-5"><?= $this->translator->translate("register_title") ?></h1>

    <h2 class="mt-5"><?= $this->translator->translate("nav_register_link") ?></h2>

    <form action="index.php?route=check-register" method="post">
        <input type="hidden" name="csrf-token" id="csrf-token" value="<?= isset($_SESSION["csrf-token"]) ?>" />
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("register_username_label") ?>
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
            <?= $this->translator->translate("register_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
            <?= $this->translator->translate("register_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control" />
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
            <?= $this->translator->translate("register_confirm_password_label") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password"  class="form-control"/>
        </fieldset>
        <fieldset>
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("register_submit_button") ?></button>
        </fieldset>
    </form>
</main>