<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php if (isset($_SESSION['user'])) { ?>
        <h1>Bienvenue</h1>
        <?= $_SESSION['nickname']; ?>
    <?php } ?>
    <fieldset>
        <a href="index.php?route=inscription">Inscription</a>
    </fieldset>
    <fieldset>
        <a href="index.php?route=connexion">Connexion</a>
    </fieldset>
    <fieldset>
        <a href="index.php?route=deconnexion">Deconnexion</a>
    </fieldset>
</body>

</html>