<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=inscription">Inscription</a>
					</li>
                    <li>
						<a href="index.php?route=connexion">Connection</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if ($route === "home") {
                require "templates/home.phtml";
            } if ($route === "inscription") {
                require "templates/register.phtml";
            } if ($route === "connexion") {
                require "templates/login.phtml";
            } if ($route === "notFound") {
                require "templates/notFound.phtml";
            }
		?>
	</body>
</html>
