<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php?route=home">Accueil</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if (!isset($_GET["route"])) {
				require "templates/home.phtml";
			}
			if ($route === "home") {
                require "templates/home.phtml";
            } if ($route === "inscription") {
                require "templates/register.phtml";
            } if ($route === "connexion") {
                require "templates/login.phtml";
            } if ($route === "deconnexion") {
				session_destroy();
                require "templates/home.phtml";
            } if ($route === "notFound") {
                require "templates/notFound.phtml";
            }
		?>
	</body>
</html>
