<h1>Connexion</h1>
<form action="logic/login.php" method="POST">
    <fieldset>
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
    </fieldset>
    <button type="submit">Se connecter</button>
</form>