<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Inscription</h1>

    <form action="controllers/register.php" method="POST">
        <fieldset>
            <label for="username">Identifiant</label>
            <input type="text" id="username" name="username" required>
        </fieldset>

        <fieldset>
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
        </fieldset>

        <fieldset>
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>
        </fieldset>

        <button type="submit">S'inscrire</button>
    </form>
</body>

</html>