<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <form action="controllers/user-form.php" method="post">
  <ul>
    <li>
      <label for="mail"></label>
      <input type="email" id="mail" name="mail" />
    </li>
    <li>
      <label for="pass"></label>
      <input type="password" id="pass" name="pass" />
    </li>
    <li>
      <button type="submit">Envoyer</button>
    </li>
  </ul>
</form>

</main>
