<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" 
    integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" 
    crossorigin="anonymous" 
    referrerpolicy="no-referrer" />
    <title>CRUD</title>
</head>
<body>
    <header>
        <p>Evite la page blanche...😅 :</p>
        <ul>
            <a href="index.php?route=create"><li>create</li></a>
            <a href="index.php?route=list"><li>list</li></a>
            <a href="index.php?route=show"><li>show</li></a>
            <a href="index.php?route=update"><li>update</li></a>
        </ul>
    </header>
    <main>
        <section>
            <?php
                if ($route === "create" || $route === "list" || $route === "show" || $route === "update") {
                    require "users/$route.phtml";
                }
            ?>
        </section>
    </main>
</body>
</html>