<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD</title>
</head>
<body>
    <?php
		if (!isset($_GET['route'])) {
			header('Location: ../index.php');
		} else {
            $route = $_GET['route'];
        }

        if ($route === 'show_user') {
            require 'users/show.phtml';
        } elseif ($route === 'create_user') {
            require 'users/create.phtml';
        } elseif ($route === 'update_user') {
            require 'users/update.phtml';
        } elseif ($route === 'delete_user') {
            require 'users/list.phtml';
        } else {
            require 'users/list.phtml';
        }
	?>
</body>
</html>