<?php require "logic/display-users.php" ?>

<table>
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom
            </th>
            <th>
                Prénom
            </th>
            <th>
                Email
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="logic/delete-user.php?id=">
                    <i class="fa-solid fa-trash"></i>
                </a>
            </td>
        </tr>
    </tbody>
</table>