<h1>Ustilisateur</h1>

<table>
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom
            </th>
            <th>
                Prénom
            </th>
            <th>
                Email
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?= $user->getId() ?></td>
            <td><?= $user->getFirstName() ?></td>
            <td><?= $user->getLastName() ?></td>
            <td><?= $user->getEmail() ?></td>
            <td>
                <a href="logic/delete-user.php?id=<?= $user->getId() ?>">
                    <i class="fa-solid fa-trash"></i>
                </a>
            </td>
        </tr>
    </tbody>
</table>