<h1>Mise à jour Utilisateur</h1>

<form action="controllers/UserController.php" method="POST">
    <fieldset>
        <label for="first_name">Nom :</label>
        <input type="text" id="first_name" name="first_name" required>
    </fieldset>

    <fieldset>
        <label for="last_name">Prénom :</label>
        <input type="text" id="last_name" name="last_name" required>
    </fieldset>

    <fieldset>
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>
    </fieldset>

    <button type="submit">Mettre à jour</button>
</form>