<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>

<body id="choice-<?= $color; ?>">
    <main>
        <section>
            <h2><?= $choiceShortSentence; ?></h2>
            <div>
                <form method="get" action="choices.php">
                    <input type="hidden" name="eventNumber" value="<?= $eventNumber; ?>" />
                    <?php foreach ($choices as $key => $choice) { ?>
                        <div>
                            <input type="radio" id="choice-<?= $key; ?>" name="choice" value="<?= $key ?>">
                            <label for="choice-<?= $key ?>"><?= $choice; ?></label>
                        </div>
                    <?php } ?>
                    <div>
                        <input type="submit" value="Valider le choix" />
                    </div>
                </form>
            </div>
        </section>
        <section>
            <section>
                <img src="<?= $eventImage; ?>" />
                <h1><?= $eventDescription; ?></h1>
            </section>
        </section>
    </main>
    <script type="application/javascript" src="assets/js/index.js"></script>
</body>

</html>