<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        Le site dont vous êtes le héros
    </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&family=Special+Elite&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css" />
</head>
<!-- gérer la couleur -->
<body id="choice-<?php echo $color; ?>">
<main>
    <section>
        <!-- afficher la question -->
        <h2><?php echo $choiceShortSentence; ?></h2>
        <div>
            <!-- adapter le formulaire avec les choix -->
            <form method="get" action="choices.php">
                <input type="hidden" name="eventNumber" value="<?php echo $eventNumber; ?>"/>
                <?php foreach($choices as $key => $choice) { ?>
                    <div>
                        <input type="radio" id="choice-<?php echo $key; ?>" name="choice" value="<?php echo $key ?>">
                        <label for="choice-<?php echo $key ?>"><?php echo $choice; ?></label>
                    </div>
                <?php } ?>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <!-- adapter avec l'image -->
            <img src="<?php echo $eventImage; ?>" />
            <!-- adapter avec la description/le récit -->
            <h1><?php echo $eventDescription; ?></h1>
        </section>
    </section>
</main>
<script type="application/javascript" src="assets/js/index.js"></script>
</body>
</html>